### ISSUE TITLE
Questions about application scenarios？

### ISSUE THREAD

**Issue by sky-fly97** [YingqianWang/Light-Field-Refocusing-A-Demo#1]
Hello, is your code used for refocusing of array cameras? Can I use this code for refocusing of light field microscope?

**Comment by YingqianWang** [comment]
Hi, thanks a lot for your attention. This code can be used for refocusing LF microscope. Taking Stanford LF microscope dataset as an example, the LFs in this dataset are organized in a macro-pixel image pattern. To use our code for refocusing, these macro-pixel images need to be first converted into sub-aperture images. You can refer to my ECCV 2020 paper ''Spatial-Angular Interaction for Light Field Image Super-Resolution'' for details of the conversion. Codes of LF-InterNet are also public available.

**Comment by sky-fly97** [comment]
> Hi, thanks a lot for your attention. This code can be used for refocusing LF microscope. Taking Stanford LF microscope dataset as an example, the LFs in this dataset are organized in a macro-pixel image pattern. To use our code for refocusing, these macro-pixel images need to be first converted into sub-aperture images. You can refer to my ECCV 2020 paper ''Spatial-Angular Interaction for Light Field Image Super-Resolution'' for details of the conversion. Codes of LF-InterNet are also public available.

Thanks， I will try！
